### ISSUE TITLE
Version 0.2.15 introduces breaking changes

### ISSUE THREAD

**Issue by castodius** [aws-samples/cdk-keycloak#123]
After upgrading from version 0.2.3 to 0.2.15 we noticed that the database was recreated. Our entire Keycloak configuration was wiped. After some trial and error I am almost certain that this was introduced in version 0.2.15 by the addition of defaultDatabaseName: 'keycloak'. This forces CloudFormation to create a new physical resource.

Steps to recreate

- Create NPM project
- Install cdk-keycloak@0.2.14
- Deploy
- Make some modifications in Keycloak
- Upgrade to cdk-keycloak@0.2.15
- Deploy
- Check the Keycloak instance, it should be now be a fresh install again

**Comment by pahud** [comment]
> After upgrading from version 0.2.3 to 0.2.15 we noticed that the database was recreated. Our entire Keycloak configuration was wiped. After some trial and error I am almost certain that this was introduced in version 0.2.15 by the addition of defaultDatabaseName: 'keycloak'. This forces CloudFormation to create a new physical resource.
> 
> Steps to recreate
> 
>     * Create NPM project
> 
>     * Install cdk-keycloak@0.2.14
> 
>     * Deploy
> 
>     * Make some modifications in Keycloak
> 
>     * Upgrade to cdk-keycloak@0.2.15
> 
>     * Deploy
> 
>     * Check the Keycloak instance, it should be now be a fresh install again

My apology not calling out the breaking changes. We will make sure all major changes subject to resource replacement will be highlighted in the breaking changes notice in the release note. Thank you for the bug report.

**Comment by wchaws** [comment]
@pahud I think we need to change all database `removalPolicy: cdk.RemovalPolicy.RETAIN`

https://github.com/aws-samples/cdk-keycloak/blob/11d2b47e6a0293c12b2b1aa40dec850177d7f033/src/keycloak.ts#L333
https://github.com/aws-samples/cdk-keycloak/blob/11d2b47e6a0293c12b2b1aa40dec850177d7f033/src/keycloak.ts#L360
https://github.com/aws-samples/cdk-keycloak/blob/11d2b47e6a0293c12b2b1aa40dec850177d7f033/src/keycloak.ts#L377
