### ISSUE TITLE
Upgrade package for aws-cdk@2

### ISSUE THREAD

**Issue by HaaLeo** [aws-samples/cdk-keycloak#162]
In my project I am using `aws-cdk@2` which is not compatible since this package uses `aws-cdk@1`. In order to also support the newer version of the CDK please upgrade this package including its peer dependencies.

**Comment by pahud** [comment]
Thank you @HaaLeo ! Yes we have to upgrade this to support CDK v2.  I am not sure if @wchaws is available for that but definitely welcome the PR if you are interested.

**Comment by pahud** [comment]
Hey @wchaws the PR is ready please take a look https://github.com/aws-samples/cdk-keycloak/pull/165

**Comment by HaaLeo** [comment]
Maybe one can reopen and review #165 ?

**Comment by dave3000** [comment]
I'm also keen to see if this can be reviewed please. @wchaws
