### ISSUE TITLE
Invalid Aurora version is hardcoded

### ISSUE THREAD

**Issue by GrandPoohBear** [aws-samples/cdk-keycloak#194]
Hello,

Currently, when deploying a stack with this Keycloak construct, I get this error:
```
Cannot find version 5.7.mysql_aurora.2.09.1 for aurora-mysql 
```
Looks like `2.09.1` is no longer listed in the dropdown for creating a new Aurora instance (2.11.2 is the latest).  Gonna try to tweak via `patch-package`, and if I find a fix that works, can open a PR.

**Comment by 094459** [comment]
+1 getting same error when I use this too.
